
CREATE TABLE IF NOT EXISTS "Order" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'new',
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  zip TEXT NOT NULL,
  waterType TEXT NOT NULL,
  bottleSize TEXT NOT NULL,
  bottlesPerDelivery TEXT NOT NULL,
  frequency TEXT NOT NULL,
  needsCooler TEXT NOT NULL,
  notes TEXT NOT NULL DEFAULT ''
);
